# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        square:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: inset
        banniere:
            quality: 80
            filters:
                upscale:
                    min: [400, 100]
                thumbnail:
                    size: [1200, 400]
                    mode: inset
        header:
            quality: 80
            filters:
                upscale:
                    min: [400, 298]
                thumbnail:
                    size: [800, 298]
                    mode: inset
