vich_uploader:
    db_driver: orm
    mappings:
        adverts_img:
            uri_prefix:         '%app.path.adverts_img%'
            upload_destination: '%kernel.project_dir%/public%app.path.adverts_img%'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
